#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-docck-plugin
Version  : 1.1
Release  : 1
URL      : https://github.com/apache/maven-docck-plugin/archive/maven-docck-plugin-1.1.tar.gz
Source0  : https://github.com/apache/maven-docck-plugin/archive/maven-docck-plugin-1.1.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-docck-plugin/1.1/maven-docck-plugin-1.1.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-docck-plugin/1.1/maven-docck-plugin-1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
No detailed description available

%prep

%build

%install

%files
%defattr(-,root,root,-)
